# Generated by Django 4.1.7 on 2023-03-14 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('creditcard', 'creditcard')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currencytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currecy', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expDateTime', models.DateField()),
                ('paymentMethod', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('creditcard', 'creditcard')], max_length=30)),
                ('status', models.CharField(choices=[('cleared', 'cleared'), ('uncleared', 'uncleared'), ('void', 'void')], max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('transactionType', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.category')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.payee')),
                ('subCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.FloatField()),
                ('default', models.CharField(max_length=50)),
                ('currencyType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Expense.currencytype')),
            ],
        ),
    ]
